version: '3.8'

services:
  frontend:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_GRAPHQL_URL=http://localhost:8080/graphql
      - NEXT_PUBLIC_KEYCLOAK_URL=http://localhost:8180
      - NEXT_PUBLIC_APP_NAME=Zplus SaaS Base
      - NEXT_PUBLIC_APP_VERSION=1.0.0
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev
    networks:
      - zplus-network

  # Optional: Storybook service
  storybook:
    build:
      context: .
      target: builder
    ports:
      - "6006:6006"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run storybook
    networks:
      - zplus-network

networks:
  zplus-network:
    external: true
